name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0       # 태그/버전 필요시
          submodules: false
          lfs: false

      - name: Sanity check (git)
        run: |
          pwd
          git --version
          git rev-parse --is-inside-work-tree
          git log --oneline -3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build
        run: ./gradlew clean build -x test

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "build/libs/*.jar"
          target: "/home/ec2-user/app"

      - name: Restart service on EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            sudo systemctl stop roarbits || true
            sudo mv /home/ec2-user/app/*.jar /home/ec2-user/roarbits.jar
            sudo systemctl start roarbits
            sudo systemctl status roarbits --no-pager -l
