name: Deploy to EC2

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fix permissions / line endings
        run: |
          sudo apt-get update -y && sudo apt-get install -y dos2unix
          dos2unix gradlew || true
          chmod +x gradlew || true

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build (Gradle)
        run: ./gradlew clean build -x test --no-daemon

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "build/libs/*.jar"
          target: "/home/ec2-user/app"

      - name: Restart service on EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            sudo systemctl stop roarbits || true
            sudo mv /home/ec2-user/app/*.jar /home/ec2-user/roarbits.jar
            sudo systemctl start roarbits
            sudo systemctl status roarbits --no-pager -l
